[package]
name = "rebxlance"
version = "0.1.0"
authors = ["Andres Orbe <aeo34@njit.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
