[package]
name = "rebxlance"
version = "0.2.0"
authors = ["Robert De Niro <dude@perfect.lol>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.pyo3]
version = "0.13.2"
features = ["auto-initialize"]